name: Pass Variable Between Stages

on: push

jobs:
  stage1:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.set_var.outputs.result }}  # <-- Correct output reference
    steps:
      - name: Set Variable
        id: set_var
        run: echo "result=Hello from Stage 1" >> $GITHUB_OUTPUT  # <-- Correct output setting

  stage2:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Use Output from Stage 1
        run: echo "Received: ${{ needs.stage1.outputs.message }}"  # <-- Correct reference
