name: Pass Variable Between Jobs

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.step1.outputs.my_variable }}
    steps:
      - name: Set Output Variable
        id: step1
        run: echo "my_variable=Hello from Job 1" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Output Variable
        run: echo "Received: ${{ needs.job1.outputs.my_variable }}"
