name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Save Terraform Plan as artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan    

      - name: Terraform Apply
        run: terraform apply -auto-approve

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: prod
    if: github.event_name == 'workflow_run'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'

      - name: Download Terraform Plan artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ./plan

      - name: Terraform Apply
        run: terraform apply -auto-approve ./plan/tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}